name: Builder ( linux/arm64/v8 )
on:
  push:
    branches: [ main ]
    paths:
      - 'builder/centos8/arm64/Dockerfile'
      - '.github/workflows/builder-centos8_arm64v8.yml'

env:
  DOCKER_HUB_TAG: xuwenkeke/builder:centos8.3.2011

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuwenkeke/docker-shxf-images
          lfs: false
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./builder/centos8/arm64/Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: |
          docker run --platform arm64 --rm ${{ env.DOCKER_HUB_TAG }} -v ./builder/centos8/arm64/:/deploy \
            echo $(arch) \
            && java -version \
            && node -v \
            && npm -v \
            && mvn -v  \
            && yarn --version \
            && gulp -v \
            && grunt -h \
            && r.js -v \
            && env \
            cd /deploy && ls -lh && yarn install 
