name: JBoss ( linux/arm64/v8 )
on:
  push:
    branches: [ main ]
    paths:
      - 'jboss/4.2/arm64/Dockerfile'
      - '.github/workflows/jboss_4.2_arm64v8.yml'

env:
  DOCKER_HUB_TAG: xuwenkeke/jboss:4.2-openjdk7-jessie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuwenkeke/docker-shxf-images
          lfs: false
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jboss/4.2/arm64/Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: |
          docker run -d --platform arm64 -p 8080:8080 --rm ${{ env.DOCKER_HUB_TAG }}
          docker container ls -a
          curl -v telnet://localhost:8080
