name: OpenJDK8
on:
  push:
    branches: [ main ]
    paths:
      - 'openjdk/8/Dockerfile'
      - '.github/workflows/openjdk8.yml'

env:
  DOCKER_HUB_TAG: xuwenkeke/openjdk:8-jdk-alpine

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuwenkeke/docker-shxf-images
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./openjdk/8/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: |
          docker pull ${{ env.DOCKER_HUB_TAG }}
          docker run --rm ${{ env.DOCKER_HUB_TAG }} --entrypoint="java -version"
