name: TongWeb7 (jdk8-oraclejdk-ubuntu22)

on:
  push:
    branches: [ main ]
    paths:
      - 'tongweb/7/jdk8-oraclejdk-ubuntu22/Dockerfile'
      - '.github/workflows/tongweb7-ubuntu22.yml'

env:
  DOCKER_FILE: 'tongweb/7/jdk8-oraclejdk-ubuntu22/Dockerfile'
  DOCKER_HUB_REPOSITORY: 'xuwenkeke/tongweb'
  DOCKER_HUB_TEST_TAG: '7-test'
  DOCKER_HUB_TAG: '7.0.4.3-ubuntu22-oraclejdk8'

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      # # Add support for more platforms with QEMU (optional)
      #   # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      # https://github.com/docker/login-action
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_REPOSITORY }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ./${{ env.DOCKER_FILE }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test TongWeb Port
        run: |
          docker run -d -p 8088:8088 -p 9060:9060 ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TAG }}
          docker container ls -a
          curl -v http://localhost:9060
          curl -v http://localhost:8088
      - name: Test2
        run: |
          docker run --rm ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TAG }} /bin/bash -x java -version && arch && ./bin/version.sh



      # # Build and Test image
      # # https://github.com/docker/build-push-action
      # - name: Build and Test image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./${{ env.DOCKER_FILE }}
      #     load: true
      #     platforms: linux/amd64
      #     tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }}
      # - name: Test TongWeb Port
      #   run: |
      #     docker run -d -p 8088:8088 -p 9060:9060 ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }}
      #     docker container ls -a
      #     curl -v http://localhost:9060
      #     curl -v http://localhost:8088
      # - name: Test2
      #   run: |
      #     docker run --rm ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }} /bin/bash -x java -version && arch && ./bin/version.sh
      
      # Build and export to Docker
      # https://github.com/docker/build-push-action   

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}