name: TongWeb7

on:
  push:
    branches: [ main ]
    paths:
      - 'tongweb/7/Dockerfile'
      - '.github/workflows/tongweb7-centos8_arm64v8.yml'

env:
  DOCKER_HUB_REPOSITORY: 'xuwenkeke/tongweb'
  DOCKER_HUB_TEST_TAG: '7-test'
  DOCKER_HUB_TAG: '7.0.4.3-centos8.3-oraclejdk8'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Validating build configuration
      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check

      # Build and export to Docker
      # https://github.com/docker/build-push-action   
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./tongweb/7/Dockerfile
          load: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }}
      
      - name: Test
        run: |
          docker run -d --platform arm64 -p 8088:8088 -p 9060:9060 ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }}
          docker container ls -a
          curl -v telnet://localhost:9060
      - name: Test2
        run: |
          docker run --platform arm64 ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TEST_TAG }} /bin/bash -x bin/version.sh

      # Login DockerHub
      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3.5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and export to Docker
      # https://github.com/docker/build-push-action   
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./tongweb/7/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_TAG }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}