name: TongWeb7
on:
  push:
    branches: [ main ]
    paths:
      - 'tongweb/7/Dockerfile'
      - '.github/workflows/tongweb7.yml'

env:
  DOCKER_HUB_TAG: xuwenkeke/tongweb:7.0.4.3-centos8.3-oraclejdk8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuwenkeke/docker-shxf-images
          lfs: false
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tongweb/7/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: | 
          docker run -d --platform arm64 -p 8088:8088 -p 9060:9060 ${{ env.DOCKER_HUB_TAG }}
          docker container ls -a
          curl -v telnet://localhost:9060
      -
        name: Test2
        run: | 
          docker run -it --platform arm64 ${{ env.DOCKER_HUB_TAG }} /bin/bash -x bin/version.sh
          